### ISSUE TITLE
Add F7DatePicker and F7Select update

### ISSUE THREAD

**Issue by Seyphaton** [RinteRface/shinyMobile#45]
Hi,
I am currently migrating my shiny project to this great shinyMobile package (great work thanks).

However, I need update functions for the datepicker and select inputs.

Thanks a lot in advance.

Best regards

**Comment by DivadNojnarg** [comment]
I take notes. Thanks for the suggestion.

**Comment by Seyphaton** [comment]
Thanks for part 1 :)

**Comment by Seyphaton** [comment]
Hey @DivadNojnarg ,

your updateF7Select implementation doesn't support the update of the available choices.
For me (and I guess a lot of other use cases) the choices change during the runtime.
Could you please add this feature aswell (and the updateF7DatePicker :) )

Best regards and thanks for your work!

**Comment by DivadNojnarg** [comment]
As soon as I manage to get the input binding working properly.

**Comment by DivadNojnarg** [comment]
Done by @pvictor

**Comment by Edireito** [comment]
Hi, first thanks for the amazing work.

Problem: I have 2 f7SmartSelect and I want the second f7SmartSelect to update the choices depending on the 1 f7SmartSelect but having trouble updating the choices with updateF7SmartSelect.

Is this update in version 0.7.0?

Minimal example:
library(shiny)
library(shinyMobile)

shinyApp(
  ui = f7Page(
    title = "My app",
    f7SingleLayout(
      navbar = f7Navbar(title = "Update f7SmartSelect"),
      f7Button("updateSmartSelect", "Update Smart Select"),
      f7SmartSelect(
        inputId = "variable",
        label = "Choose a variable:",
        selected = "drat",
        choices = colnames(mtcars)[-1],
        openIn = "popup"
      ),
      tableOutput("data")
    )
  ),
  server = function(input, output, session) {
    output$data <- renderTable({
      mtcars[, c("mpg", input$variable), drop = FALSE]
    }, rownames = TRUE)
    
    observeEvent(input$updateSmartSelect, {
      updateF7SmartSelect(
        inputId = "variable",
        openIn = "sheet",
        selected = "cyl",
        choices = c("cyl","teste1"),
        multiple = TRUE,
        maxLength = 3
      )
    })
  }
)

**Comment by khbrc** [comment]
Hi.  I understood from this thread that it's possible to update "choices" when using updateF7Select.  I'm finding that option to be unavailable.  When I attempt to specify a new selection of choices I get "Error in updateF7Select: unused argument (choices = c(... " and the app crashes.  Is there an ongoing issue or have I misunderstood this conversation?

**Comment by grcatlin** [comment]
The issue @khbrc mentions where they cannot update F7Select choices is still an issue for me. Will this be fixed?
